### ISSUE TITLE
Unable to reach server in secure connection

### ISSUE THREAD

**Issue by carlosrve** [Odoo-mobile/messaging#15]
I get the "unable to reach odoo server" error using secure connection. My server is behind an Apache reverse proxy doing SSL with a valid and signed certificate. The certificate chain is working, I checked my certificate fully with online checkers. But the app keeps saying that the cert is wrong, and then it says that it was unable to reach the server. Looking on the server log, this is what is happening:

The app is trying to list the database in http mode, not in json:

2014-09-22 16:14:01,815 14616 ERROR tierrafirme werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
execute(self.server.app)
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
application_iter = app(environ, start_response)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/service/wsgi_server.py", line 214, in application
return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
File "/usr/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 144, in call
return self.app(environ, start_response)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
result = handler(environ, start_response)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 1214, in call
return self.dispatch(environ, start_response)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 1188, in call
return self.app(environ, start_wrapped)
File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in call
return self.app(environ, start_response)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 1355, in dispatch
result = ir_http._dispatch()
File "/srv/odoo/8.0/instances/tierrafirme/odoo/addons/crm/ir_http.py", line 13, in _dispatch
response = super(ir_http, self)._dispatch()
File "/srv/odoo/8.0/instances/tierrafirme/odoo/addons/website/models/ir_http.py", line 125, in _dispatch
return super(ir_http, self)._dispatch()
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/addons/base/ir/ir_http.py", line 130, in _dispatch
return self._handle_exception(e)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/addons/website/models/ir_http.py", line 201, in _handle_exception
return super(ir_http, self)._handle_exception(exception)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
return request._handle_exception(exception)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 595, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
result = request.dispatch()
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 613, in dispatch
r = self._call_function(**self.params)
File "/srv/odoo/8.0/instances/tierrafirme/odoo/openerp/http.py", line 264, in _call_function
% (self.endpoint.original, self.httprequest.path, self.endpoint.routing['type'], self._request_type))
Exception: , /web/webclient/version_info: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

**Comment by ecwashburn** [comment]
Is anyone working on this issue?  I am trying to connect to my own Odoo v8 instance with ODOO web app and I am having a simular problem.

Exception: <function version_info at 0xb507cbc4>, /web/webclient/version_info: Function declared as capable of handling request of type 'json' but called with a request of type 'http'

**Comment by dpr-odoo** [comment]
Hello,

Issue has been fixed https://github.com/Odoo-mobile/framework/commit/badd412ca04553a915975dbb50a2cfb0635c8c8c. Update available soon on playstore.

**Comment by tytgatlieven** [comment]
Dear 

Is this update released in the play store? 
I still notice the same behavior 

Kind regards

**Comment by saravanan10393** [comment]
HI ecwashburn ,  dpr-odoo , 

```
   I am also getting same error  " /web/webclient/version_info: Function declared as capable of handling request of type 'json' but called with a request of type 'http' "  in odoo web when i call this from this library "https://github.com/akretion/angular-odoo/blob/master/dist/odoo.js" which is simple Ajax request. If any body solved this issue please help me. 
```

**Comment by ellaguno** [comment]
I just tryied the app with my Self hosted Odoo and receive the same error (Unable to reach ...), with 2 different installs, one with SSL and the other without, one with Apache reverse Proxy and the other without.
